#!/usr/bin/env bash
# Sends a "week in review" digest once per week, Monday 0800 Eastern.
#
# Same design as daily_digest.sh: run hourly via cron, self-gate on the
# local Eastern day-of-week + hour, with an ISO-week state file so it only
# fires once per calendar week even if cron double-fires in the 8 o'clock
# hour. America/New_York (DST-aware) rather than a fixed UTC offset so it
# tracks 8am wall-clock across the March/November changes.
#
# The body is Beacon's own week: wakings, commits, lines changed, and what
# shipped -- generated by website/build_weekly.py --text from NOTES.md and
# git history, the same source the /weekly.html page is built from.
#
# KIT NOTE: website/build_weekly.py is NOT included in this starter kit --
# it's a small custom script that reads NOTES.md + `git log` and prints a
# text summary. Don't add this one to cron until you've written that
# script (or asked Gemini to write one for your setup); until then it will
# just fail every Monday. See SETUP_GUIDE.md, "Optional extras."
set -uo pipefail
cd /home/agent/agent || exit 1

STATE_FILE=".weekly_digest_sent"
WEEK_ET="$(TZ=America/New_York date +%G-W%V)"
DOW_ET="$(TZ=America/New_York date +%u)"   # 1 = Monday
HOUR_ET="$(TZ=America/New_York date +%H)"

[ "$DOW_ET" = "1" ] || exit 0
[ "$HOUR_ET" = "08" ] || exit 0
[ -f "$STATE_FILE" ] && [ "$(cat "$STATE_FILE")" = "$WEEK_ET" ] && exit 0

mkdir -p logs
if BODY="$(python3 website/build_weekly.py --text 2>>logs/weekly_digest.log)"; then
    ./notify.sh "$BODY" >>logs/weekly_digest.log 2>&1 && echo "$WEEK_ET" >"$STATE_FILE"
else
    echo "$(date -u +%FT%TZ) build_weekly.py --text failed" >>logs/weekly_digest.log
fi
